# see docs: https://docs.docker.com/engine/reference/builder/

FROM node:lts-alpine

# https://mirrors.ustc.edu.cn/help/alpine.html
RUN sed -i 's/http:\/\/dl-cdn.alpinelinux.org/https:\/\/mirrors.ustc.edu.cn/g' /etc/apk/repositories

# install dependencies
RUN apk update \
    && apk add --no-cache --virtual .build-deps curl \
    && curl -sf https://gobinaries.com/tj/node-prune | sh \
    && apk del .build-deps