# HTTP Test (VS Code Plugin: REST Client)

###

GET http://localhost:3000/api HTTP/1.1

###

POST http://localhost:3000/api HTTP/1.1

###

PUT http://localhost:3000/api HTTP/1.1

###

DELETE http://localhost:3000/api HTTP/1.1